### ISSUE TITLE
对话时出现错误，错误提示如下：

### ISSUE THREAD

**Issue by sion934** [TomLBZ/koishi-plugin-openai#25]
2023-03-08 06:55:56 [W] session 在不在
                        Error: Invalid encoding
                            at module.exports.__wbindgen_error_new (/koishi/node_modules/@dqbd/tiktoken/dist/node/_tiktoken.js:414:17)
                            at wasm://wasm/00fdfe62:wasm-function[30]:0x2bd1f
                            at wasm://wasm/00fdfe62:wasm-function[235]:0x5bafb
                            at module.exports.get_encoding (/koishi/node_modules/@dqbd/tiktoken/dist/node/_tiktoken.js:160:14)
                            at Eye.basePrompt (/koishi/node_modules/@tomlbz/koishi-plugin-openai/lib/eye.js:108:49)
                            at /koishi/node_modules/@tomlbz/koishi-plugin-openai/lib/index.js:87:30
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:853:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:853:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:853:16)

**Comment by sion934** [comment]
重启koishi之后正常了。。。。感觉应该是koishi有内存溢出问题，出现问题的时候koishi占用内存特别高，重启之后内存占用恢复正常了，之后测试没有出现这个问题。

**Comment by TomLBZ** [comment]
> 重启koishi之后正常了。。。。感觉应该是koishi有内存溢出问题，出现问题的时候koishi占用内存特别高，重启之后内存占用恢复正常了，之后测试没有出现这个问题。

噢噢没问题就太好啦ヽ(✿ﾟ▽ﾟ)ノ

**Comment by MirrorCY** [comment]
> 重启koishi之后正常了。。。。感觉应该是koishi有内存溢出问题，出现问题的时候koishi占用内存特别高，重启之后内存占用恢复正常了，之后测试没有出现这个问题。

我似乎知道一个已知的内存占用问题，你可以试试能否解决
https://github.com/koishijs/console/issues/50

**Comment by sion934** [comment]
> > 重启koishi之后正常了。。。。感觉应该是koishi有内存溢出问题，出现问题的时候koishi占用内存特别高，重启之后内存占用恢复正常了，之后测试没有出现这个问题。
> 
> 我似乎知道一个已知的内存占用问题，你可以试试能否解决 [koishijs/console#50](https://github.com/koishijs/console/issues/50)

嗯嗯，我已经将别的插件都清理了，只保留了基础插件和这个插件，再观察看看，谢谢。
