### ISSUE TITLE
Error: Request failed with status code 401

### ISSUE THREAD

**Issue by DAIORANGE** [TomLBZ/koishi-plugin-openai#7]
```
2022-12-13 17:35:42 [W] session <at id="1027199591"/> hi
                        Error: Request failed with status code 401
                            at createError (C:\Users\alfina-server\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\openai\node_modules\axios\lib\core\createError.js:16:15)
                            at settle (C:\Users\alfina-server\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\openai\node_modules\axios\lib\core\settle.js:17:12)
                            at IncomingMessage.handleStreamEnd (C:\Users\alfina-server\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\openai\node_modules\axios\lib\adapters\http.js:322:11)
                            at IncomingMessage.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1358:12)
                            at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

作者你好，机器人对话没有反应，api是用搭在机器人电脑（国内ip但路由器上有科学上网）访问openai官网f12 获取的__Secure-next-auth.session-token后面的value值。
请问这个问题是因为我的ip还是[最近openai官网添加了cloudflare浏览器检测导致的](https://github.com/acheong08/ChatGPT)
或者其他原因？

**Comment by MirrorCY** [comment]
你回复的流程是使用插件 https://github.com/koishijs/chatgpt-bot  的流程，请到对应的仓库提出 issue

**Comment by MirrorCY** [comment]
cc @TomLBZ

**Comment by TomLBZ** [comment]
不属于这个仓库
